import { DatabaseSchema } from './db';
import {
  ONBMember,
  ONBGroup,
  WorkSchedule,
  WorkTypeCatalog,
  ProgressTask,
  Customer,
  CustomerPackage,
  MonthlyBonus,
  TrainingPackage,
  ReferenceScore,
  DEFAULT_SCHEDULE_WORK_FORMS,
  DEFAULT_TRAINING_MODULES,
  DEFAULT_RECURRING_SCHEDULES
} from '../src/types';
import { RAW_SCHEDULE_CSV, parseCsvSchedules } from './parseExcelSchedule';

export function getInitialSeedData(): DatabaseSchema {
  const groups: ONBGroup[] = [
    { id: 'grp_1', code: 'NHOM_1', name: 'Nhóm 1', order: 1, isActive: true, description: 'Nhóm nghiệp vụ 1' },
    { id: 'grp_2', code: 'NHOM_2', name: 'Nhóm 2', order: 2, isActive: true, description: 'Nhóm nghiệp vụ 2' },
    { id: 'grp_3', code: 'NHOM_3', name: 'Nhóm 3', order: 3, isActive: true, description: 'Nhóm nghiệp vụ 3' }
  ];

  const members: ONBMember[] = [
    {
      id: 'ONB_DTHANG',
      code: 'DTHANG',
      fullName: 'Từ Đức Thắng',
      displayName: 'Từ Đức Thắng (Admin)',
      shortCode: 'DTHANG',
      email: 'Thangtutu0201@gmail.com',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-01-01', note: 'Gia nhập ONB' }],
      startDate: '2025-01-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'HRM', 'Kế toán', 'Sản xuất', 'Kho', 'Mua hàng', 'Quy trình', 'Wesign'],
      phone: '0901234567'
    },
    {
      id: 'ONB_NDDUONG',
      code: 'NDDUONG',
      fullName: 'Nguyễn Đại Dương',
      displayName: 'NĐDƯƠNG',
      shortCode: 'NĐDƯƠNG',
      email: 'duong.nd@onb.company.vn',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-01-01' }],
      startDate: '2025-01-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'Kho', 'Sản xuất', 'AI MKT'],
      phone: '0901234568'
    },
    {
      id: 'ONB_LIEM',
      code: 'LIEM',
      fullName: 'Nguyễn Thanh Liêm',
      displayName: 'LIÊM',
      shortCode: 'LIÊM',
      email: 'liem.nt@onb.company.vn',
      currentGroup: 'Nhóm 2',
      groupHistory: [{ group: 'Nhóm 2', fromDate: '2025-01-01' }],
      startDate: '2025-01-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['HRM', 'Chấm công', 'Tiền lương', 'Tuyển dụng'],
      phone: '0901234569'
    },
    {
      id: 'ONB_DTPTHAO',
      code: 'DTPTHAO',
      fullName: 'Đoàn Thị Phương Thảo',
      displayName: 'DTPTHAO',
      shortCode: 'DTPTHAO',
      email: 'thao.dtp@onb.company.vn',
      currentGroup: 'Nhóm 3',
      groupHistory: [{ group: 'Nhóm 3', fromDate: '2025-01-01' }],
      startDate: '2025-01-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'Sản xuất', 'HRM', 'Kho', 'Mua hàng'],
      phone: '0901234570'
    },
    {
      id: 'ONB_NTGIANG',
      code: 'NTGIANG',
      fullName: 'Nguyễn Thị Giang',
      displayName: 'NTGIANG',
      shortCode: 'NTGIANG',
      email: 'giang.nt@onb.company.vn',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-01-01' }],
      startDate: '2025-01-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Sản xuất', 'Giá thành', 'Kho', 'HRM', 'Kiểm toán'],
      phone: '0901234571'
    },
    {
      id: 'ONB_DCLOI',
      code: 'DCLOI',
      fullName: 'Đỗ Cao Lợi',
      displayName: 'ĐCLỢI',
      shortCode: 'ĐCLỢI',
      email: 'loi.dc@onb.company.vn',
      currentGroup: 'Nhóm 2',
      groupHistory: [{ group: 'Nhóm 2', fromDate: '2025-01-01' }],
      startDate: '2025-01-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Sản xuất', 'CRM', 'Wesign', 'Kế toán', 'Kho'],
      phone: '0901234572'
    },
    {
      id: 'ONB_THANH_HUYEN',
      code: 'THANH_HUYEN',
      fullName: 'Nguyễn Thanh Huyền',
      displayName: 'THANH.HUYEN',
      shortCode: 'THANH.HUYEN',
      email: 'huyen.nt@onb.company.vn',
      currentGroup: 'Nhóm 3',
      groupHistory: [{ group: 'Nhóm 3', fromDate: '2025-02-01' }],
      startDate: '2025-02-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Kế toán', 'CRM', 'Mua hàng', 'Quy trình'],
      phone: '0901234573'
    },
    {
      id: 'ONB_THUE',
      code: 'THUE',
      fullName: 'Trần Thị Huế',
      displayName: 'T.HUE',
      shortCode: 'T.HUE',
      email: 'hue.tt@onb.company.vn',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-02-01' }],
      startDate: '2025-02-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Kế toán', 'CRM', 'TTNS', 'Thuế', 'Quy trình'],
      phone: '0901234574'
    },
    {
      id: 'ONB_BTHUONG',
      code: 'BTHUONG',
      fullName: 'Bùi Thị Hương',
      displayName: 'BT.HƯƠNG',
      shortCode: 'BT.HƯƠNG',
      email: 'huong.bt@onb.company.vn',
      currentGroup: 'Nhóm 2',
      groupHistory: [{ group: 'Nhóm 2', fromDate: '2025-02-01' }],
      startDate: '2025-02-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'Quy trình', 'Kế toán', 'Giá thành'],
      phone: '0901234575'
    },
    {
      id: 'ONB_VQUAN',
      code: 'VQUAN',
      fullName: 'Vũ Văn Quân',
      displayName: 'V.QUAN',
      shortCode: 'V.QUAN',
      email: 'quan.vv@onb.company.vn',
      currentGroup: 'Nhóm 3',
      groupHistory: [{ group: 'Nhóm 3', fromDate: '2025-02-01' }],
      startDate: '2025-02-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'Kho', 'Sản xuất', 'Mua hàng', 'Văn Thư'],
      phone: '0901234576'
    },
    {
      id: 'ONB_PHDUY',
      code: 'PHDUY',
      fullName: 'Phạm Hoàng Duy',
      displayName: 'PHDUY',
      shortCode: 'PHDUY',
      email: 'duy.ph@onb.company.vn',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-03-01' }],
      startDate: '2025-03-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'Wesign', 'Quy trình', 'MAKT'],
      phone: '0901234577'
    },
    {
      id: 'ONB_HXDAT',
      code: 'HXDAT',
      fullName: 'Hoàng Xuân Đạt',
      displayName: 'HXĐAT',
      shortCode: 'HXĐAT',
      email: 'dat.hx@onb.company.vn',
      currentGroup: 'Nhóm 2',
      groupHistory: [{ group: 'Nhóm 2', fromDate: '2025-03-01' }],
      startDate: '2025-03-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['HRM', 'Chấm công', 'Tiền lương', 'Công việc'],
      phone: '0901234578'
    },
    {
      id: 'ONB_NPTHAO',
      code: 'NPTHAO',
      fullName: 'Nguyễn Phương Thảo',
      displayName: 'NPTHAO',
      shortCode: 'NPTHAO',
      email: 'thao.np@onb.company.vn',
      currentGroup: 'Nhóm 3',
      groupHistory: [{ group: 'Nhóm 3', fromDate: '2025-03-01' }],
      startDate: '2025-03-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['TTNS', 'Chấm công', 'Tiền lương', 'HRM'],
      phone: '0901234579'
    },
    {
      id: 'ONB_THANHAN',
      code: 'THANHAN',
      fullName: 'Nguyễn Thành An',
      displayName: 'THANHAN',
      shortCode: 'THANHAN',
      email: 'an.nt@onb.company.vn',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-04-01' }],
      startDate: '2025-04-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['HRM', 'CRM', 'Wesign', 'Quy trình', 'Tiền lương'],
      phone: '0901234580'
    },
    {
      id: 'ONB_MINHDUC',
      code: 'MINHDUC',
      fullName: 'Lê Minh Đức',
      displayName: 'MINHDUC',
      shortCode: 'MINHDUC',
      email: 'duc.lm@onb.company.vn',
      currentGroup: 'Nhóm 2',
      groupHistory: [{ group: 'Nhóm 2', fromDate: '2025-04-01' }],
      startDate: '2025-04-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Kế toán', 'Kho hàng', 'Mua hàng', 'CRM'],
      phone: '0901234581'
    },
    {
      id: 'ONB_THUHUYEN',
      code: 'THUHUYEN',
      fullName: 'Nguyễn Thu Huyền',
      displayName: 'THUHUYEN',
      shortCode: 'THUHUYEN',
      email: 'huyen.th@onb.company.vn',
      currentGroup: 'Nhóm 3',
      groupHistory: [{ group: 'Nhóm 3', fromDate: '2025-04-01' }],
      startDate: '2025-04-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['CRM', 'HRM', 'Công việc', 'Chấm công'],
      phone: '0901234582'
    },
    {
      id: 'ONB_THANHTHAO',
      code: 'THANHTHAO',
      fullName: 'Trần Thanh Thảo',
      displayName: 'THANHTHAO',
      shortCode: 'THANHTHAO',
      email: 'thao.tt@onb.company.vn',
      currentGroup: 'Nhóm 1',
      groupHistory: [{ group: 'Nhóm 1', fromDate: '2025-05-01' }],
      startDate: '2025-05-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['HRM', 'Công việc', 'CRM', 'Tiền lương'],
      phone: '0901234583'
    },
    {
      id: 'ONB_HNHUNG',
      code: 'HNHUNG',
      fullName: 'Hoàng Hồng Nhung',
      displayName: 'H.NHUNG',
      shortCode: 'H.NHUNG',
      email: 'nhung.hh@onb.company.vn',
      currentGroup: 'Nhóm 2',
      groupHistory: [{ group: 'Nhóm 2', fromDate: '2025-05-01' }],
      startDate: '2025-05-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Wesign', 'Công việc', 'Kế toán', 'Quy trình'],
      phone: '0901234584'
    },
    {
      id: 'ONB_NKLINH',
      code: 'NKLINH',
      fullName: 'Nguyễn Khánh Linh',
      displayName: 'NKLINH',
      shortCode: 'NKLINH',
      email: 'linh.nk@onb.company.vn',
      currentGroup: 'Nhóm 3',
      groupHistory: [{ group: 'Nhóm 3', fromDate: '2025-06-01' }],
      startDate: '2025-06-01',
      isActive: true,
      participateRandom: true,
      completedProducts: ['Kế toán', 'Hệ thống'],
      phone: '0901234585'
    }
  ];

  const products = [
    { id: 'p_crm', code: 'CRM', name: 'Quản lý quan hệ khách hàng (CRM)', category: 'CRM' as const, isActive: true },
    { id: 'p_hrm', code: 'HRM', name: 'Quản trị nhân sự tổng thể (HRM)', category: 'HRM' as const, isActive: true },
    { id: 'p_ttns', code: 'TTNS', name: 'Thông tin nhân sự', category: 'HRM' as const, isActive: true },
    { id: 'p_cc', code: 'CHẤM CÔNG', name: 'Chấm công', category: 'HRM' as const, isActive: true },
    { id: 'p_tl', code: 'TIỀN LƯƠNG', name: 'Tính lương & Thuế', category: 'HRM' as const, isActive: true },
    { id: 'p_kho', code: 'KHO', name: 'Quản lý kho hàng', category: 'ERP' as const, isActive: true },
    { id: 'p_mua', code: 'MUA', name: 'Quản lý mua hàng', category: 'ERP' as const, isActive: true },
    { id: 'p_sx', code: 'SẢN XUẤT', name: 'Quản lý sản xuất & Định mức', category: 'ERP' as const, isActive: true },
    { id: 'p_kt', code: 'KẾ TOÁN', name: 'Kế toán tài chính', category: 'ERP' as const, isActive: true },
    { id: 'p_ts', code: 'TÀI SẢN', name: 'Quản lý tài sản & CCDC', category: 'Module' as const, isActive: true },
    { id: 'p_qt', code: 'QUY TRÌNH', name: 'Quản lý quy trình động', category: 'Module' as const, isActive: true },
    { id: 'p_ws', code: 'WESIGN', name: 'Chữ ký số & Trình ký WeSign', category: 'Module' as const, isActive: true },
    { id: 'p_cv', code: 'CÔNG VIỆC', name: 'Quản lý công việc & Dự án', category: 'Module' as const, isActive: true },
    { id: 'p_aimkt', code: 'AI MKT', name: 'AI Marketing & Bán hàng', category: 'Module' as const, isActive: true },
    { id: 'p_vps', code: 'VPS', name: 'Hạ tầng máy chủ VPS', category: 'Other' as const, isActive: true },
    { id: 'p_vt', code: 'VĂN THƯ', name: 'Văn thư lưu trữ', category: 'Module' as const, isActive: true },
    { id: 'p_bhxh', code: 'BHXH', name: 'Bảo hiểm xã hội & Thuế TNCN', category: 'HRM' as const, isActive: true }
  ];

  const workTypes: WorkTypeCatalog[] = [
    { id: 'wt_tvtk_tt', code: 'TVTK_TT', name: 'Tư vấn triển khai trực tiếp', isTraining: false, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'TVTK Trực tiếp', defaultScorePerUnit: 10, order: 1 },
    { id: 'wt_tvtk_tinh', code: 'TVTK_Tỉnh', name: 'Tư vấn triển khai tỉnh', isTraining: false, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'TVTK Tỉnh', defaultScorePerUnit: 12, order: 2 },
    { id: 'wt_tvtk_on11', code: 'TVTK_ON11', name: 'Tư vấn triển khai Online 1-1', isTraining: false, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'ON11', defaultScorePerUnit: 8, order: 3 },
    { id: 'wt_dttt', code: 'ĐTTT', name: 'Đào tạo tập trung', isTraining: true, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'Đào tạo tập trung', defaultScorePerUnit: 8, order: 4 },
    { id: 'wt_on11', code: 'ON11', name: 'Đào tạo Online 1-1', isTraining: true, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'ON11', defaultScorePerUnit: 6, order: 5 },
    { id: 'wt_tt', code: 'Trực tiếp', name: 'Làm việc trực tiếp tại KH', isTraining: false, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'TVTK Trực tiếp', defaultScorePerUnit: 10, order: 6 },
    { id: 'wt_ht', code: 'HT', name: 'Hỗ trợ nghiệp vụ / hệ thống', isTraining: false, isActive: true, unit: 'Giờ', unitType: 'hours', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'Hỗ trợ HT', defaultScorePerUnit: 5, order: 7 },
    { id: 'wt_poc', code: 'POC', name: 'Xây dựng dữ liệu mẫu POC', isTraining: false, isActive: true, unit: 'Gói', unitType: 'number', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'DEMO/POC/Tiền về', defaultScorePerUnit: 15, order: 8 },
    { id: 'wt_dtkn', code: 'ĐTKN', name: 'Đào tạo kỹ năng nội bộ', isTraining: true, isActive: true, unit: 'Buổi', unitType: 'session', calculationMethod: 'QUANTITY_MULTIPLY', requiresProduct: false, kpiCategory: 'Đào tạo nội bộ', defaultScorePerUnit: 8, order: 9 },
    { id: 'wt_tien_ve', code: 'TIEN_VE', name: 'Tiền về', isTraining: false, isActive: true, unit: 'VNĐ', unitType: 'currency', calculationMethod: 'AMOUNT_DIVIDE', requiresProduct: false, kpiCategory: 'DEMO/POC/Tiền về', defaultScorePerUnit: 1, order: 10 }
  ];

  const referenceScores: ReferenceScore[] = [
    { id: 'rs_1', workTypeCode: 'TVTK_TT', suggestedScore: 10, effectiveFrom: '2026-01-01', description: 'Triển khai trực tiếp tiêu chuẩn' },
    { id: 'rs_2', workTypeCode: 'TVTK_Tỉnh', suggestedScore: 12, effectiveFrom: '2026-01-01', description: 'Triển khai ngoại tỉnh (công tác)' },
    { id: 'rs_3', workTypeCode: 'TVTK_ON11', suggestedScore: 8, effectiveFrom: '2026-01-01', description: 'Triển khai online 1-1' },
    { id: 'rs_4', workTypeCode: 'ĐTTT', suggestedScore: 8, effectiveFrom: '2026-01-01', description: 'Đào tạo tập trung lớp phòng' },
    { id: 'rs_5', workTypeCode: 'ON11', suggestedScore: 6, effectiveFrom: '2026-01-01', description: 'Hướng dẫn online 1-1' },
    { id: 'rs_6', workTypeCode: 'Trực tiếp', suggestedScore: 10, effectiveFrom: '2026-01-01', description: 'Làm việc tại khách hàng' },
    { id: 'rs_7', workTypeCode: 'POC', suggestedScore: 15, effectiveFrom: '2026-01-01', description: 'Xây dựng demo POC chuyên sâu' },
    { id: 'rs_8', workTypeCode: 'HT', suggestedScore: 5, effectiveFrom: '2026-01-01', description: 'Hỗ trợ kỹ thuật / giải đáp' },
    { id: 'rs_tien_ve', workTypeCode: 'TIEN_VE', suggestedScore: 1, conversionRate: 5000000, effectiveFrom: '2026-01-01', description: 'Quy đổi Tiền về: 5.000.000 VNĐ = 1 điểm KPI' }
  ];

  const customers: Customer[] = [
    { id: 'cust_novatech', code: 'KH_NOVATECH', name: 'Công ty Cổ phần Novatech Vina', taxCode: '0108923412', contactPerson: 'Anh Hoàng (GĐ)', phone: '0912345678', createdAt: '2026-06-01' },
    { id: 'cust_toyoink', code: 'KH_TOYOINK', name: 'Công ty TNHH Toyo Ink Việt Nam', taxCode: '0304567890', contactPerson: 'Chị Mai (KTT)', phone: '0912345679', createdAt: '2026-06-15' },
    { id: 'cust_decovina', code: 'KH_DECOVINA', name: 'Công ty Cổ phần Deco Vina', taxCode: '0106543210', contactPerson: 'Anh Kiên', phone: '0912345680', createdAt: '2026-06-20' },
    { id: 'cust_crowe', code: 'KH_CROWE', name: 'Công ty Kiểm toán Crowe Việt Nam', taxCode: '0101239874', contactPerson: 'Chị Lan', phone: '0912345681', createdAt: '2026-06-25' },
    { id: 'cust_toancau', code: 'KH_TOANCAU', name: 'Tập đoàn Toàn Cầu', taxCode: '0109876543', contactPerson: 'Anh Hùng', phone: '0912345682', createdAt: '2026-06-28' },
    { id: 'cust_ducphat', code: 'KH_DUCPHAT', name: 'Công ty TNHH Đức Phát', taxCode: '0203456789', contactPerson: 'Anh Phát', phone: '0912345683', createdAt: '2026-07-01' },
    { id: 'cust_hoanglong', code: 'KH_HOANGLONG', name: 'Công ty Nhôm Kính Hoàng Long Ninh Bình', taxCode: '2700876543', contactPerson: 'Anh Long', phone: '0912345684', createdAt: '2026-07-10' },
    { id: 'cust_daihaeung', code: 'KH_DAIHAEUNG', name: 'Công ty TNHH Dai Hae Ung', taxCode: '2300987654', contactPerson: 'Mr. Lee / Chị Vân', phone: '0912345685', createdAt: '2026-07-05' },
    { id: 'cust_thanhtrang', code: 'KH_THANHTRANG', name: 'Công ty TNHH Dược Phẩm Thanh Trang', taxCode: '0107654321', contactPerson: 'Anh Thắng', phone: '0912345686', createdAt: '2026-07-15' },
    { id: 'cust_hoadang', code: 'KH_HOADANG', name: 'Tập đoàn Hoa Đăng Group', taxCode: '0108877665', contactPerson: 'Chị Phương', phone: '0912345687', createdAt: '2026-08-01' },
    { id: 'cust_hanmy', code: 'KH_HANMY', name: 'Công ty Thẩm mỹ Hân Mỹ', taxCode: '0312349988', contactPerson: 'Chị Hân', phone: '0912345688', createdAt: '2026-08-10' },
    { id: 'cust_quanghanh', code: 'KH_QUANGHANH', name: 'Công ty Cổ phần Đầu tư Quang Hanh', taxCode: '3200112233', contactPerson: 'Anh Hạnh', phone: '0912345689', createdAt: '2026-08-15' }
  ];

  const packages: CustomerPackage[] = [
    {
      id: 'pkg_novatech_01',
      packageCode: 'GOI-2026-001',
      customerId: 'cust_novatech',
      packageName: 'Tiếp nhận triển khai HRM & Tiền lương',
      packageType: 'Mới tiếp nhận',
      assignedOnbCode: 'NTGIANG',
      handoverHistory: [{ onbCode: 'NTGIANG', fromDate: '2026-07-01', note: 'Tiếp nhận từ Sale' }],
      receptionDate: '2026-07-01',
      monthYear: '2026-07',
      status: 'Đang triển khai',
      suggestedScore: 20,
      recordedScore: 20,
      splits: [],
      createdAt: '2026-07-01',
      updatedAt: '2026-07-01',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'pkg_toyoink_01',
      packageCode: 'GOI-2026-002',
      customerId: 'cust_toyoink',
      packageName: 'Triển khai Phân hệ Kho & Mua hàng',
      packageType: 'Mới tiếp nhận',
      assignedOnbCode: 'NTGIANG',
      handoverHistory: [{ onbCode: 'NTGIANG', fromDate: '2026-07-02' }],
      receptionDate: '2026-07-02',
      monthYear: '2026-07',
      status: 'Đang triển khai',
      suggestedScore: 18,
      recordedScore: 18,
      splits: [],
      createdAt: '2026-07-02',
      updatedAt: '2026-07-02',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'pkg_thanhtrang_01',
      packageCode: 'GOI-2026-003',
      customerId: 'cust_thanhtrang',
      packageName: 'Gói triển khai tổng thể CRM & Chấm công',
      packageType: 'Đang phụ trách',
      assignedOnbCode: 'DCLOI',
      handoverHistory: [{ onbCode: 'DCLOI', fromDate: '2026-07-15' }],
      receptionDate: '2026-07-15',
      monthYear: '2026-07',
      status: 'Đang triển khai',
      suggestedScore: 25,
      recordedScore: 25,
      splits: [{ onbCode: 'DCLOI', points: 15, note: 'Phụ trách chính CRM' }, { onbCode: 'LIEM', points: 10, note: 'Hỗ trợ chấm công' }],
      createdAt: '2026-07-15',
      updatedAt: '2026-07-15',
      updatedBy: 'DCLOI'
    },
    {
      id: 'pkg_hoadang_01',
      packageCode: 'GOI-2026-004',
      customerId: 'cust_hoadang',
      packageName: 'Gói triển khai ERP Tổng thể Hoa Đăng',
      packageType: 'Mới tiếp nhận',
      assignedOnbCode: 'DTHANG',
      handoverHistory: [{ onbCode: 'DTHANG', fromDate: '2026-09-01' }],
      receptionDate: '2026-09-01',
      monthYear: '2026-09',
      status: 'Đang triển khai',
      suggestedScore: 30,
      recordedScore: 30,
      splits: [],
      createdAt: '2026-09-01',
      updatedAt: '2026-09-01',
      updatedBy: 'DTHANG'
    },
    {
      id: 'pkg_quanghanh_01',
      packageCode: 'GOI-2026-005',
      customerId: 'cust_quanghanh',
      packageName: 'Gói triển khai CRM & Kho Quảng Ninh',
      packageType: 'Mới tiếp nhận',
      assignedOnbCode: 'NDDUONG',
      handoverHistory: [{ onbCode: 'NDDUONG', fromDate: '2026-10-01' }],
      receptionDate: '2026-10-01',
      monthYear: '2026-10',
      status: 'Đang triển khai',
      suggestedScore: 22,
      recordedScore: 22,
      splits: [],
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01',
      updatedBy: 'NDDUONG'
    }
  ];

  // Schedules populated with real data from Excel
  const schedules: WorkSchedule[] = [
    // 29/06 - 05/07
    {
      id: 'sch_1',
      onbCode: 'NDDUONG',
      collaborators: [],
      date: '2026-07-03',
      workTypeCode: 'ON11',
      productCode: 'CRM',
      customerOrTask: 'demo notarlic',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-03',
      updatedBy: 'NDDUONG'
    },
    {
      id: 'sch_2',
      onbCode: 'DTPTHAO',
      collaborators: [],
      date: '2026-06-30',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'HRM',
      customerOrTask: 'ĐỨC PHÁT',
      status: 'Hoàn thành',
      monthYear: '2026-06',
      createdAt: '2026-06-30',
      updatedAt: '2026-06-30',
      updatedBy: 'DTPTHAO'
    },
    {
      id: 'sch_3',
      onbCode: 'DTPTHAO',
      collaborators: [],
      date: '2026-07-01',
      workTypeCode: 'TVTK_ON11',
      productCode: 'HRM',
      customerOrTask: 'POC HONDA TÂY HỒ',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-01',
      updatedBy: 'DTPTHAO'
    },
    {
      id: 'sch_4',
      onbCode: 'DTPTHAO',
      collaborators: [],
      date: '2026-07-02',
      workTypeCode: 'TVTK_TT',
      productCode: 'SẢN XUẤT',
      customerOrTask: 'Xây dl Deco vina',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-02',
      updatedBy: 'DTPTHAO'
    },
    {
      id: 'sch_5',
      onbCode: 'DTPTHAO',
      collaborators: [],
      date: '2026-07-03',
      workTypeCode: 'TVTK_TT',
      productCode: 'SẢN XUẤT',
      customerOrTask: 'DECO VINA',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-03',
      updatedBy: 'DTPTHAO'
    },
    {
      id: 'sch_6',
      onbCode: 'NTGIANG',
      collaborators: [],
      date: '2026-06-29',
      workTypeCode: 'TVTK_TT',
      productCode: 'TIỀN LƯƠNG',
      customerOrTask: 'NOVATECH',
      status: 'Hoàn thành',
      monthYear: '2026-06',
      createdAt: '2026-06-29',
      updatedAt: '2026-06-29',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'sch_7',
      onbCode: 'NTGIANG',
      collaborators: [],
      date: '2026-06-30',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'KHO',
      customerOrTask: 'TOYOINK',
      status: 'Hoàn thành',
      monthYear: '2026-06',
      createdAt: '2026-06-30',
      updatedAt: '2026-06-30',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'sch_8',
      onbCode: 'NTGIANG',
      collaborators: [],
      date: '2026-07-01',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'KHO',
      customerOrTask: 'TOYOINK',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-01',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'sch_9',
      onbCode: 'NTGIANG',
      collaborators: [],
      date: '2026-07-02',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'SẢN XUẤT',
      customerOrTask: 'DTK HẠ LONG',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-02',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'sch_10',
      onbCode: 'NTGIANG',
      collaborators: [],
      date: '2026-07-03',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'SẢN XUẤT',
      customerOrTask: 'DTK HẠ LONG',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-03',
      updatedBy: 'NTGIANG'
    },
    // V.QUAN
    {
      id: 'sch_11',
      onbCode: 'VQUAN',
      collaborators: [],
      date: '2026-06-29',
      workTypeCode: 'ĐTTT',
      productCode: 'QUY TRÌNH',
      customerOrTask: 'QT + WS',
      status: 'Hoàn thành',
      monthYear: '2026-06',
      createdAt: '2026-06-29',
      updatedAt: '2026-06-29',
      updatedBy: 'VQUAN'
    },
    {
      id: 'sch_12',
      onbCode: 'VQUAN',
      collaborators: [],
      date: '2026-06-30',
      workTypeCode: 'TVTK_TT',
      productCode: 'CRM',
      customerOrTask: 'NAAN',
      status: 'Hoàn thành',
      monthYear: '2026-06',
      createdAt: '2026-06-30',
      updatedAt: '2026-06-30',
      updatedBy: 'VQUAN'
    },
    {
      id: 'sch_13',
      onbCode: 'VQUAN',
      collaborators: [],
      date: '2026-07-02',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'MUA',
      customerOrTask: 'DAI HAE UNG',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-02',
      updatedBy: 'VQUAN'
    },
    {
      id: 'sch_14',
      onbCode: 'VQUAN',
      collaborators: [],
      date: '2026-07-03',
      workTypeCode: 'ĐTTT',
      productCode: 'CRM',
      customerOrTask: 'Lớp cơ bản 1 CRM',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-03',
      updatedBy: 'VQUAN'
    },
    // HXDAT
    {
      id: 'sch_15',
      onbCode: 'HXDAT',
      collaborators: [],
      date: '2026-06-30',
      workTypeCode: 'ĐTTT',
      productCode: 'TTNS',
      customerOrTask: 'CROWE',
      status: 'Hoàn thành',
      monthYear: '2026-06',
      createdAt: '2026-06-30',
      updatedAt: '2026-06-30',
      updatedBy: 'HXDAT'
    },
    {
      id: 'sch_16',
      onbCode: 'HXDAT',
      collaborators: [],
      date: '2026-07-02',
      workTypeCode: 'ĐTTT',
      productCode: 'CHẤM CÔNG',
      customerOrTask: 'CROWE',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-02',
      updatedBy: 'HXDAT'
    },
    // NPTHAO
    {
      id: 'sch_17',
      onbCode: 'NPTHAO',
      collaborators: [],
      date: '2026-07-03',
      workTypeCode: 'Trực tiếp',
      productCode: 'TTNS',
      customerOrTask: 'TOÀN CẦU',
      status: 'Hoàn thành',
      monthYear: '2026-07',
      createdAt: '2026-07-01',
      updatedAt: '2026-07-03',
      updatedBy: 'NPTHAO'
    },
    // Current month 2026-10 schedule records
    {
      id: 'sch_current_1',
      onbCode: 'DTHANG',
      collaborators: ['LIEM'],
      date: '2026-10-05',
      startTime: '08:30',
      endTime: '11:30',
      workTypeCode: 'POC',
      productCode: 'CRM',
      customerOrTask: 'GLIFEFOOD',
      notes: 'Khởi động dự án POC CRM chuỗi cung ứng thực phẩm',
      status: 'Hoàn thành',
      monthYear: '2026-10',
      createdAt: '2026-10-04',
      updatedAt: '2026-10-05',
      updatedBy: 'DTHANG'
    },
    {
      id: 'sch_current_2',
      onbCode: 'NDDUONG',
      collaborators: [],
      date: '2026-10-05',
      startTime: '13:30',
      endTime: '17:00',
      workTypeCode: 'TVTK_ON11',
      productCode: 'CRM',
      customerOrTask: 'Demo Euro style',
      status: 'Hoàn thành',
      monthYear: '2026-10',
      createdAt: '2026-10-04',
      updatedAt: '2026-10-05',
      updatedBy: 'NDDUONG'
    },
    {
      id: 'sch_current_3',
      onbCode: 'LIEM',
      collaborators: [],
      date: '2026-10-06',
      startTime: '09:00',
      endTime: '11:30',
      workTypeCode: 'POC',
      productCode: 'HRM',
      customerOrTask: 'AUMI - 9h',
      status: 'Kế hoạch',
      monthYear: '2026-10',
      createdAt: '2026-10-04',
      updatedAt: '2026-10-04',
      updatedBy: 'LIEM'
    },
    {
      id: 'sch_current_4',
      onbCode: 'DTPTHAO',
      collaborators: [],
      date: '2026-10-05',
      startTime: '08:00',
      endTime: '12:00',
      workTypeCode: 'HT',
      productCode: 'SẢN XUẤT',
      customerOrTask: 'HOÀNG LIÊN',
      status: 'Hoàn thành',
      monthYear: '2026-10',
      createdAt: '2026-10-04',
      updatedAt: '2026-10-05',
      updatedBy: 'DTPTHAO'
    },
    {
      id: 'sch_current_5',
      onbCode: 'NTGIANG',
      collaborators: [],
      date: '2026-10-05',
      startTime: '08:30',
      endTime: '11:30',
      workTypeCode: 'TVTK_ON11',
      productCode: 'KHO',
      customerOrTask: 'TÂM AN',
      status: 'Hoàn thành',
      monthYear: '2026-10',
      createdAt: '2026-10-04',
      updatedAt: '2026-10-05',
      updatedBy: 'NTGIANG'
    },
    {
      id: 'sch_current_6',
      onbCode: 'DCLOI',
      collaborators: [],
      date: '2026-10-05',
      startTime: '08:00',
      endTime: '17:00',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'KẾ TOÁN',
      customerOrTask: 'Phú Quý',
      status: 'Hoàn thành',
      monthYear: '2026-10',
      createdAt: '2026-10-04',
      updatedAt: '2026-10-05',
      updatedBy: 'DCLOI'
    }
  ];

  const parsedFromCsv = parseCsvSchedules(RAW_SCHEDULE_CSV);
  const allSchedules: WorkSchedule[] = [...schedules];
  for (const ps of parsedFromCsv) {
    if (!allSchedules.some(s => s.onbCode === ps.onbCode && s.date === ps.date && s.customerOrTask === ps.customerOrTask)) {
      allSchedules.push(ps);
    }
  }

  const progress: ProgressTask[] = [
    {
      id: 'prg_1',
      code: 'TD-2026-001',
      taskName: 'Tư vấn triển khai trực tiếp DECO VINA',
      customerId: 'cust_decovina',
      primaryOnbCode: 'DTPTHAO',
      workTypeCode: 'TVTK_TT',
      productCode: 'SẢN XUẤT',
      date: '2026-07-03',
      monthYear: '2026-07',
      status: 'Hoàn thành',
      suggestedScore: 10,
      recordedScore: 10,
      splits: [],
      notes: 'Triển khai thành công quy trình sản xuất cơ khí',
      scheduleId: 'sch_5',
      createdAt: '2026-07-03',
      updatedAt: '2026-07-03',
      updatedBy: 'DTPTHAO'
    },
    {
      id: 'prg_2',
      code: 'TD-2026-002',
      taskName: 'Đào tạo tập trung Lớp cơ bản 1 CRM',
      primaryOnbCode: 'VQUAN',
      workTypeCode: 'ĐTTT',
      productCode: 'CRM',
      date: '2026-07-03',
      monthYear: '2026-07',
      status: 'Hoàn thành',
      suggestedScore: 8,
      recordedScore: 10, // User entered different score
      splits: [
        { onbCode: 'VQUAN', points: 6, note: 'Giảng viên chính' },
        { onbCode: 'THANHAN', points: 4, note: 'Trợ giảng & hỗ trợ thực hành' }
      ],
      notes: 'Lớp 25 học viên, hỗ trợ tận tình',
      scheduleId: 'sch_14',
      createdAt: '2026-07-03',
      updatedAt: '2026-07-03',
      updatedBy: 'VQUAN'
    },
    {
      id: 'prg_current_1',
      code: 'TD-2026-101',
      taskName: 'POC Khởi động GLIFEFOOD CRM & Supply',
      primaryOnbCode: 'DTHANG',
      workTypeCode: 'POC',
      productCode: 'CRM',
      date: '2026-10-05',
      monthYear: '2026-10',
      status: 'Hoàn thành',
      suggestedScore: 15,
      recordedScore: 16,
      splits: [
        { onbCode: 'DTHANG', points: 10, note: 'Kiến trúc giải pháp' },
        { onbCode: 'LIEM', points: 6, note: 'Xây dữ liệu nhân sự' }
      ],
      notes: 'Dự án mẫu quan trọng trong tháng 10',
      scheduleId: 'sch_current_1',
      createdAt: '2026-10-05',
      updatedAt: '2026-10-05',
      updatedBy: 'DTHANG'
    },
    {
      id: 'prg_current_2',
      code: 'TD-2026-102',
      taskName: 'Tư vấn triển khai tỉnh Phú Quý Kế toán & Mua hàng',
      primaryOnbCode: 'DCLOI',
      workTypeCode: 'TVTK_Tỉnh',
      productCode: 'KẾ TOÁN',
      date: '2026-10-05',
      monthYear: '2026-10',
      status: 'Hoàn thành',
      suggestedScore: 12,
      recordedScore: 12,
      splits: [],
      notes: 'Khách hàng đánh giá tốt',
      scheduleId: 'sch_current_6',
      createdAt: '2026-10-05',
      updatedAt: '2026-10-05',
      updatedBy: 'DCLOI'
    }
  ];

  const bonuses: MonthlyBonus[] = [
    {
      id: 'bn_202607_1',
      monthYear: '2026-07',
      onbCode: 'NTGIANG',
      amount: 2000000,
      reason: 'Thưởng xuất sắc triển khai dự án Novatech',
      updatedBy: 'DTHANG',
      updatedAt: '2026-07-31'
    },
    {
      id: 'bn_202607_2',
      monthYear: '2026-07',
      onbCode: 'DTPTHAO',
      amount: 1500000,
      reason: 'Thưởng vượt chỉ tiêu số lượt TVTK trực tiếp',
      updatedBy: 'DTHANG',
      updatedAt: '2026-07-31'
    },
    {
      id: 'bn_202608_1',
      monthYear: '2026-08',
      onbCode: 'DCLOI',
      amount: 2500000,
      reason: 'Thưởng hoàn thành tiến độ khách hàng trọng điểm',
      updatedBy: 'DTHANG',
      updatedAt: '2026-08-31'
    },
    {
      id: 'bn_202609_1',
      monthYear: '2026-09',
      onbCode: 'DTHANG',
      amount: 3000000,
      reason: 'Thưởng điều hành dự án lớn toàn phòng',
      updatedBy: 'DTHANG',
      updatedAt: '2026-09-30'
    },
    {
      id: 'bn_202610_1',
      monthYear: '2026-10',
      onbCode: 'LIEM',
      amount: 1200000,
      reason: 'Thưởng hỗ trợ khởi động tháng 10',
      updatedBy: 'DTHANG',
      updatedAt: '2026-10-04'
    }
  ];

  const trainingPackages: TrainingPackage[] = [
    {
      id: 'tp_1',
      packageCode: 'ĐTTT-10-01',
      productCode: 'CRM',
      moduleName: 'Quản trị quan hệ khách hàng (CRM)',
      sessionOfDay: 'Chiều',
      title: 'Đào tạo tập trung CRM Cơ bản (Lớp Tháng 10)',
      monthYear: '2026-10',
      scheduledDate: '2026-10-14',
      scheduledTime: '14:00 - 17:00',
      allocationPoints: 10,
      assignedOnbCode: 'VQUAN',
      assignedGroup: 'Nhóm 3',
      isLocked: false,
      allocationStatus: 'Đã phân bổ',
      scheduleStatus: 'Chưa điền lịch',
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01'
    },
    {
      id: 'tp_2',
      packageCode: 'ĐTTT-10-02',
      productCode: 'HRM',
      moduleName: 'Quản trị nhân sự tổng thể (HRM)',
      sessionOfDay: 'Sáng',
      title: 'Đào tạo Chấm công & Tiền lương nâng cao',
      monthYear: '2026-10',
      scheduledDate: '2026-10-15',
      scheduledTime: '09:00 - 12:00',
      allocationPoints: 12,
      assignedOnbCode: 'LIEM',
      assignedGroup: 'Nhóm 2',
      isLocked: true, // Locked assignment
      allocationStatus: 'Đã phân bổ',
      scheduleStatus: 'Chưa điền lịch',
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01'
    },
    {
      id: 'tp_3',
      packageCode: 'ĐTTT-10-03',
      productCode: 'SẢN XUẤT',
      moduleName: 'Quản lý sản xuất & Định mức',
      sessionOfDay: 'Chiều',
      title: 'Đào tạo Định mức & Kế hoạch sản xuất',
      monthYear: '2026-10',
      scheduledDate: '2026-10-16',
      scheduledTime: '14:00 - 17:00',
      allocationPoints: 12,
      assignedOnbCode: 'NTGIANG',
      assignedGroup: 'Nhóm 1',
      isLocked: false,
      allocationStatus: 'Đã phân bổ',
      scheduleStatus: 'Chưa điền lịch',
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01'
    },
    {
      id: 'tp_4',
      packageCode: 'ĐTTT-10-04',
      productCode: 'WESIGN',
      moduleName: 'Chữ ký số & Trình ký WeSign',
      sessionOfDay: 'Sáng',
      title: 'Đào tạo Trình ký & Luồng số hóa WeSign',
      monthYear: '2026-10',
      scheduledDate: '2026-10-21',
      scheduledTime: '09:00 - 12:00',
      allocationPoints: 8,
      allocationStatus: 'Chưa phân bổ',
      scheduleStatus: 'Chưa điền lịch',
      isLocked: false,
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01'
    },
    {
      id: 'tp_5',
      packageCode: 'ĐTTT-10-05',
      productCode: 'KẾ TOÁN',
      moduleName: 'Kế toán tài chính',
      sessionOfDay: 'Chiều',
      title: 'Đào tạo Nghiệp vụ Bán hàng - Mua hàng - Kế toán',
      monthYear: '2026-10',
      scheduledDate: '2026-10-22',
      scheduledTime: '14:00 - 17:00',
      allocationPoints: 10,
      allocationStatus: 'Chưa phân bổ',
      scheduleStatus: 'Chưa điền lịch',
      isLocked: false,
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01'
    },
    {
      id: 'tp_6',
      packageCode: 'ĐTTT-10-06',
      productCode: 'AI MKT',
      moduleName: 'AI Marketing & Bán hàng',
      sessionOfDay: 'Chiều',
      title: 'Đào tạo Ứng dụng AI trong Chăm sóc khách hàng tự động',
      monthYear: '2026-10',
      scheduledDate: '2026-10-28',
      scheduledTime: '14:00 - 17:00',
      allocationPoints: 10,
      allocationStatus: 'Chưa phân bổ',
      scheduleStatus: 'Chưa điền lịch',
      isLocked: false,
      createdAt: '2026-10-01',
      updatedAt: '2026-10-01'
    }
  ];

  return {
    config: {
      adminEmail: 'Thangtutu0201@gmail.com',
      adminOnbCode: 'DTHANG',
      bonusManagers: ['LIEM', 'DTPTHAO'],
      allocationManagers: ['NTGIANG', 'NDDUONG'],
      timezone: 'Asia/Ho_Chi_Minh',
      systemLockedMonths: ['2026-01', '2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08', '2026-09'],
      initialDataImportLocked: false
    },
    groups,
    members,
    products,
    workTypes,
    scheduleWorkForms: JSON.parse(JSON.stringify(DEFAULT_SCHEDULE_WORK_FORMS)),
    referenceScores,
    schedules: allSchedules,
    progress,
    customers,
    packages,
    bonuses,
    bonusPools: [],
    trainingModules: JSON.parse(JSON.stringify(DEFAULT_TRAINING_MODULES)),
    isTrainingModulesInitialized: true,
    recurringTrainingSchedules: JSON.parse(JSON.stringify(DEFAULT_RECURRING_SCHEDULES)),
    isRecurringTrainingInitialized: true,
    trainingPackages,
    auditLogs: [
      {
        id: 'log_init',
        timestamp: '2026-10-05T08:00:00+07:00',
        action: 'CREATE',
        entity: 'CORE',
        entityId: 'SYSTEM',
        onbCode: 'DTHANG',
        userName: 'Từ Đức Thắng',
        description: 'Khởi tạo hệ thống Quản lý Vận hành phòng ONB với dữ liệu lịch sử từ 01/2026'
      }
    ]
  };
}
